### ISSUE TITLE
Alt-F4 on Windows can trigger a Windows popup reporting that the application was malfunctioning

### ISSUE THREAD

**Issue by tomreyn** [MegaGlest/megaglest-source#103]
When you hit Alt-F4 on some menus, those which do networking, you may run into a Windows generated error message reporting that the program has stopped working, and that Windows is searching for a solution to the problem (which takes some seconds after which it reports that it could not find one).

I assume this is related to the IRC thread not closing down cleanly in this case.

This kind of (technically minor) issue adds to the unpolished feeling on Windows.

**Comment by softcoder** [comment]
Please provide specific use cases hat can reproduce this error. I tried loading the Internet menu from win7 and both alt-f4 or Clicking window X both close the game without error for me.

**Comment by tomreyn** [comment]
I recorded [a video](http://tomreyn.megaglest.org/windows_altf4_crash.mkv) on Windows which demonstrates this issue (first crash around 00m30s). This 50 MB download shows how MG crashes on windows in two different ways when pressing Alt-F4. 

Half of the video is actually me trying to get the debugger to work (and failing) - sorry abut that.

**Comment by softcoder** [comment]
I have added more verbose output, please reproduce again with --verbose and provide the console output

**Comment by tomreyn** [comment]
Thanks to Softcoders' efforts, I can no longer reproduce this issue since d5f915f.
