### ISSUE TITLE
FreeBSD, runtime error related with haptic support

### ISSUE THREAD

**Issue by filux** [MegaGlest/megaglest-source#105]
Since switching to SDL2 I had a problem during launch game binary (FreeBSD 10.2 - latest stable) because of error like:
```SDL not built with haptic (force feedback) support.```
Game can't be successfully launched and by this impossible is test of the status for issues #72 and #73 .

Error is pretty clear and for users mean: ~ "broken sdl2 port", so 
- first step was upgrade of freebsd ports but this didn't change the situation,
- next step (many hints from the BSD topics) was try to build sdl2 from ports' source with not disabled haptic in options and I found out haptic was enabled by default and this also didn't didn't change the situation (funny is like people are writing "compilation with haptic helped", good joke you bsd-trolls :P),
- third attempt was try to compile SDL2-2.0.4 from original source but it is not possible because missing patches which if get from ports seems to be not fully compatible.

Then I found this bug report which seems to be close to true: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=200854

So Imo if it is possible we need something like:
``` c++
If [ not BSD ]; then SDL_INIT_HAPTIC; fi
```
or for now MG is not supporting BSD anymore (I am curious how bsd-trolls will see this xD).

**Comment by monwarez** [comment]
One thing I does not understand, why MegaGlest need force feedback ?

**Comment by filux** [comment]
Well as I know MG doesn't need it (at least yet) but simple "init all" is very tempting :smiley: when all works on linux & windows & macos where are done most/all of our tests.

Do you know something about that: does someone is working on adding HAPTIC support for BSD? and how advanced is such work?

**Comment by monwarez** [comment]
I made a port update for 3.12.0: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=205485 , with the previous patch. From what I understand, the problem with HAPTIC support is that its use some GNU/Linux specific events (I suppose in kernel space ?), and I know that FreeBSD is not intended to be a GNU/Linux OS. I think it will be necessary to add HAPTIC support in SDL2 code directly.

**Comment by monwarez** [comment]
Do you have this issue with the version 3.12.0 on the port ? issues: https://github.com/MegaGlest/megaglest-source/issues/72, and https://github.com/MegaGlest/megaglest-source/issues/73

**Comment by filux** [comment]
Hehe, I am not a FreeBSD user :). Feel free to comment those issues about, can you reproduce them or not. Two voices are better than 1 ;).
...and v3.12.0 is based on later commit than tests were done :).

My last test was done ~ creation date of this issue and was related only with this issue.

**Comment by monwarez** [comment]
I am sure that I don't have issue https://github.com/MegaGlest/megaglest-source/issues/73 (maybe it was OpenAL fault after all) , for the other https://github.com/MegaGlest/megaglest-source/issues/72 , I need to launch it on a terminal to see if error pop up.
