### ISSUE TITLE
clicking X doesn't cancel building structure

### ISSUE THREAD

**Issue by andy5995** [MegaGlest/megaglest-source#110]
I noticed this when I click on "build castle" when my intent is to click "build advanced structure".

I accidentally click on "build castle" but then see my mistake (the shadow of the castle appears). I click the X to cancel, but instead, my worker starts to build the castle in the area behind the X (provided the area is clear and I have enough resources, as what would normally happen).

**Comment by filux** [comment]
I can't reproduce this on 3.12.0

**Comment by filux** [comment]
Ok, reproduced, but for me it is not a bug, you are trying to "cancel worker's job before told him what to do", just "click X two times" (then second time will do the job) or use "right mouse click" instead.

**Comment by andy5995** [comment]
I understand. My apologies for the false report.
