### ISSUE TITLE
Game crashes when exiting from networked menus on Windows10

### ISSUE THREAD

**Issue by titiger** [MegaGlest/megaglest-source#111]
I have got reports that the game crashes on exit in windows 10.
On windows7 64bit I cannot see this behaviour.

**Comment by filux** [comment]
Sounds pretty serious but without any additional info like "how to reproduce"/"crash message"/"verbose output" most issues like this (in other/every issue trackers) are usually closed  (very fast) with note "not enough info".

**Comment by andy5995** [comment]
Filux, I have Windows 10 - I'll get you some additional info by the end of the day.

**Comment by andy5995** [comment]
1. I ran Megaglest, and then at the main menu, I exited. No crash.

2. I ran MegaGlest, and proceeded to the Internet menu. I waited for IRC to connect. 

3. I backed out: return -> return -> exit

4 MegaGlest closed, but I received a few Windows dialog boxes. I can't copy and paste them, the first one says "MegaGlest has encountered and error... windows is checking for a solution to the problem"

Then that dialog box changes and flashes related information very briefly, and finally one box remains "megaglestx64.exe has stopped working - A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available." I click the close button on the Windows dialog box and my terminal prompt is clear. No need to use ctrl-c.

I ran mg with the verbose option. Here is a plain text file with the output.
https://drive.google.com/file/d/0B-Ixr8t8mjDsOVBvUEN2RXJiTVk/view?usp=sharing

**Comment by andy5995** [comment]
On or around December 29, 2015, I tested a Win 10 x64 development snapshot with titi. I'm sure I would have noticed this crash; which means the bug was introduced at some point within the last 30 days.

After five times of going to the lobby and then exiting (without playing or joining a server) the bug reproduces every time.

**Comment by filux** [comment]
Imo looks like problem is at least similar to #103 
.+ on the beginning I see info about "not used MG's registry fix". Did you use installer?

**Comment by andy5995** [comment]
Yes, today when I tested, I used the 3.12.0 installer.

I didn't use the dev installer when I tested with titi last month.

Maybe something was left behind from running the game from the snapshot last month?

The same problem happened on my nephew's computer when I ran the installer snapshot two days before the release of 3.12.0. He previously had installed 3.11.1 for Windows x64, which I removed (using the control panel -> add/remove programs) before installing the dev snapshot.

**Comment by tomreyn** [comment]
I am able to reproduce this reliably this on Windows 10 x64 using the 3.12.0 installer-created 64-bit game. The steps to reproduce this are indeed very similar to those discussed in #103, and exactly as discussed above by Andy:
* Start game in GUI mode
* Advance to main menu
* Navigate to New Game -> Internet Game
* Press Alt-F4 at any time
* Windows crash reporter triggers

**Comment by filux** [comment]
at least seems to be related,
["nig":](https://forum.megaglest.org/index.php?topic=9806.msg92426#msg92426)
> go to the MG-Gameserver-Lobby,
> press windows key,
> Close MG by using the return and exit buttons,
> >>>> MG crashes after closing its screens.
> 
> 3.12-dev is affected with this issues too.

**Comment by andy5995** [comment]
While testing rev 5444.ad4314f I noted that this error also happens when using the custom game option.

It first happened 2 weeks ago on 3.12 stable (on my mom's laptop, installing MG for the first time).

I just now reproduced it.

softcoder, the verbose output is attached.


[MG_Win10_20160602-andy_5995-01.zip](https://github.com/MegaGlest/megaglest-source/files/296292/MG_Win10_20160602-andy_5995-01.zip)

**Comment by andy5995** [comment]
[MG_5451-1621e56-111.zip](https://github.com/MegaGlest/megaglest-source/files/296644/MG_5451-1621e56-111.zip)

**Comment by andy5995** [comment]
My nephew told me that this is a common feature to games on Windows 10. He said it happens on a lot of games.

**Comment by filux** [comment]
During yesterday's tests Issh & Jammy couldn't reproduce this on dev version (probably on snapshot in both cases) ... so looks like probably it was fixed btw fixing the other bug.

**Comment by IsshMG** [comment]
I have this issue in version 3.12 when I exit the game. This is for all games, not just network games. 

This issue is now solved in the dev version.

**Comment by titiger** [comment]
Looks like this is fixed now
