### ISSUE TITLE
Increase maximum zoomout distance

### ISSUE THREAD

**Issue by Imarok** [MegaGlest/megaglest-source#114]
It would very usefull for the gameplay to increase the maximum zoomout distance.[](url)

**Comment by alketii** [comment]
You can by adding this to glestuser.ini

```
CameraFov=45.00
CameraInvertXAxis=true
CameraInvertYAxis=true
CameraMaxDistance=35.00
CameraMaxYaw=77.50
CameraMinDistance=8.00
CameraMinYaw=20.00
CameraMoveSpeed=15
```

**Comment by Imarok** [comment]
What about adding this as setting?

**Comment by Imarok** [comment]
I made this a pull request. (https://github.com/MegaGlest/megaglest-source/pull/115)
Hope I did everything right as i am new to github ;)

**Comment by titiger** [comment]
The pull request was ok, but I don't want to merge it (see my reasons in pull request)

I close this "issue" too now because it is like it should be and by this no issue.
