### ISSUE TITLE
deselecting scenario from host menu can lead to crash

### ISSUE THREAD

**Issue by andy5995** [MegaGlest/megaglest-source#122]
In the pic attached, this set-up happened after I deselected (unchecked) an 8-player scenario. A 6 player map came up. The 7th and 8th slot is empty, but the AI difficulty number (2.5) is shown. If a user clicks to start a game, MG will crash.

![screen8](https://cloud.githubusercontent.com/assets/16764864/15875437/7b51450c-2ccd-11e6-8c8f-a99228a80845.jpg)

**Comment by softcoder** [comment]
This issue is now fixed
