### ISSUE TITLE
Documentation brush up

### ISSUE THREAD

**Issue by tomreyn** [MegaGlest/megaglest-source#127]
Some of the documentation shipping with the game is getting outdated and should be rewritten. Suggestions welcome.

**Comment by CaseyVanderham** [comment]
Hi Tom, I would love to help out! Is there anything that needs a lot of attention?

**Comment by tomreyn** [comment]
Thanks for offering your help, Casey.
When you read the text files in the docs/ subdirectory of this repository and the megaglest-data one, you will probably notice that some of them were not written by native English speakers. So rephrasing them would be nice, reducing bulky / complex sentences to shorter ones or just to concise statements. 

Also obvious stuff could be removed, obviously missing information added. We run a wiki at [docs.megaglest.org](https://docs.megaglest.org) which may provide some info lacking from the README's. Also, playing the game can probably give you a good hint on what's lacking / unneccessary.

**Comment by salman-bhai** [comment]
Hey, is this issue still open for contributions? @CaseyVanderham

**Comment by tomreyn** [comment]
We've accepted contributions on this by @Qwertee and @vjon. More are always welcome (just push a PR, or open an issue about it in advance to discuss), but since hacktoberfest is over, I'll close this issue.
