### ISSUE TITLE
Fog of war issues when game has ended

### ISSUE THREAD

**Issue by titiger** [MegaGlest/megaglest-source#135]
If you win a game the fog of war should be lifted for the whole map. Same thing should happen if you loose all units. 
Both things worked with 3.12.0 but not with git anymore.

**Comment by titiger** [comment]
How to easily reproduce:
Just start a game with only you as only faction. You instantly get "you won" but the fog of war is not lifted.

**Comment by softcoder** [comment]
Cannot reproduce this using these steps. As soon as i see you won fog of war is lifted for me on current build.

**Comment by filux** [comment]
I can reproduce this.
```
$ ./megaglest
megaglest v3.12-dev
Compiled using: GNUC: 60200 [64bit] platform: Linux-X64 endianness: little
GIT: [Rev: 5494.7a64569] - using STREFLOP [SSE] - [no-denormals]
```

![screen15](https://cloud.githubusercontent.com/assets/5335953/19837937/9001850c-9ec4-11e6-8ce5-89a3bcb35a03.png)

**Comment by softcoder** [comment]
Yes now i can, but only if i start in the first slot
