### ISSUE TITLE
MG 3.12.0, Ubuntu 16.10: fails to detect LAN IPv4 address

### ISSUE THREAD

**Issue by tomreyn** [MegaGlest/megaglest-source#137]
As previously discussed on [Ubuntu bug #1639411](https://bugs.launchpad.net/ubuntu/+source/megaglest/+bug/1639411), MegaGlest 3.12.0 fails to detect the systems primary IPv4 address on Ubuntu 16.10. 

I was able to reproduce this on a Virtualbox VM with IPv4 192.168.2.15 assigned to its only (besides loopback) NIC enp0s3, using both the installer downloaded from megaglest.org and the Ubuntu package.

**Comment by softcoder** [comment]
Looks like this is already fixed in the latest git code, please retest.

**Comment by softcoder** [comment]
This issue no longer exists and was fixed last year.
