### ISSUE TITLE
pressing key acts as 2 key presses (or double-key toggle)

### ISSUE THREAD

**Issue by andy5995** [MegaGlest/megaglest-source#143]
I didn't see there was a ticket created for this yet. I remember it was discussed in the #megaglest IRC channel.

I believe it was decided by the developers that libSDL2  was the cause.

IIRC, it happened sometimes when someone tried toggling team chat.

For me, it is happening right now on 3.12 when I press K from the host menu to turn the game music off. The result is that the music doesn't turn off.

A few times, I noticed it was happening in-game when I would hit p to pause and resume the game. Though I didn't make a mental note if I was on git or not.

For 3.12, I'm using the version I downloaded from megaglest.org. I used to primarily run 3.12 as my own build.

I was using Debian 8 (Jessie) and yesterday upgraded to 9 (testing). The double p's happened while on Debian 8.

**Comment by titiger** [comment]
Hm is this the same issue? : https://github.com/MegaGlest/megaglest-source/issues/139

**Comment by andy5995** [comment]
@titiger tells me this bug is fixed in the git version, and this error doesn't reproduce for me on git. closing ticket.
