### ISSUE TITLE
pressing 'x' key sometimes produces no sound

### ISSUE THREAD

**Issue by andy5995** [MegaGlest/megaglest-source#144]
i've noticed more than a few times that pressing 'x' and clicking on the map (sometimes) produces no sound.

Jammy commented in IRC that he also has noticed this.

I tried reproducing in a game with filux today, but failed.

If anyone else notices this on the git version, please mention it, and try to note what you were doing at the time.

I can't say exactly what I was doing at the time, but will pay more attention in the future.

Update: this happened again today during the first game of the day on git. It only seems to happen during battle, so I assume a sound conflict.

I have yet to determine if other players hear the sound, even though it doesn't sound for the person pressing the 'x'.

Update: this happened to me on 3.12 today

**Comment by titiger** [comment]
Technical problem with this is we cannot playback all needed sounds. You typically can play back 5,8 or whatever sounds side by side ( depends on hardware ). So if units are fighting you hear sounds form every unit and ... the alarm sound. But if there are already too many "normal" sounds in the queue you don't playback of the important alarm sound is not played back. At the moment I have no idea how to fix it. Maybe we can play back sounds with different priority or something like this or keep one sound channel free for those important sounds.

**Comment by andy5995** [comment]
Understood. I assume this means it will sound for the other players, unless they too have too many sounds at that time.

**Comment by titiger** [comment]
I tried to fix it, please test and give feedback.

**Comment by andy5995** [comment]
Some testing, but not much yet. So far, so good.

**Comment by andy5995** [comment]
I'm not sure yet. Sometimes it seems not to work, but works a lot more reliably and frequently than before.

**Comment by titiger** [comment]
so I mark this as fixed for now ?

**Comment by andy5995** [comment]
Yes.
