### ISSUE TITLE
When asterisk "*" key is used, Ibis is invisible or partly missing

### ISSUE THREAD

**Issue by andy5995** [MegaGlest/megaglest-source#145]
Here when they are fighting, they are completely invisible:
https://postimg.org/image/5rudb8pg1/

Here when they are idle, they are partially invisible:
https://postimg.org/image/jpdle38wv/

filux says
> maybe good idea will be to test this also when "you are the other color"

**Comment by titiger** [comment]
should be fixed in git

**Comment by andy5995** [comment]
tested, works for me.
