### ISSUE TITLE
if initial reset is greater than 1 when randomizing height, stacktrace dialog appears

### ISSUE THREAD

**Issue by andy5995** [MegaGlest/megaglest-source#146]
In the map editor, if initial reset is greater than 1 when randomizing height, stacktrace dialog appears

[![Screenshot_2017-02-05_00-10-05.png](https://s23.postimg.org/qxf11vau3/Screenshot_2017_02_05_00_10_05.png)](https://postimg.org/image/4y8mentzr/)

**Comment by softcoder** [comment]
Should be fixed in next build, commit to git now (now any value 1 or higher will means true)

**Comment by andy5995** [comment]
Looks good!
