### ISSUE TITLE
map editor - undo function sometimes does not work

### ISSUE THREAD

**Issue by andy5995** [MegaGlest/megaglest-source#148]
For certain features, using _undo_ from the _edit_ menu doesn't produce expected results:

1. If a player's position is changed, and undo is immediately used, clicking _undo_ does nothing
2. if _randomize height_ is used 1x, _undo_ does nothing unless clicked 2x
3. If the map is resized, and _undo_ is immediate used, it does nothing.

**Comment by titiger** [comment]
1. is known and will not be fixed ( its a bit complicated and I see no real benefit )
2. is fixed 
3. In my eyes 3 should be a full reset and its ok you cannot undo it in my opinion. Problem is currently its not a full reset. ( I see no benefit to keep a part of the map in editor when resizing ).

**Comment by titiger** [comment]
I vote to remove the resize possibility. Just use "new" to start a map of different size. Real resize makes no sense in my opinion.

**Comment by andy5995** [comment]
I could adjust to that; new -> resize. I vote ok if it makes things easier

**Comment by andy5995** [comment]
@titiger fixed this with https://github.com/MegaGlest/megaglest-source/commit/da48cfe9ce51e6c518fc1f2df99f0479aa88a860

Closing.
