### ISSUE TITLE
mini-map in game is not always proportionate to map geometry

### ISSUE THREAD

**Issue by andy5995** [MegaGlest/megaglest-source#165]
The mini-map is not proportioned correctly unless the actual map is a square.

It doesn't cause much problems on 128x256 maps, I think, but on maps with a higher difference of dimensions it can become more challenging to use the mini-map.

**Comment by titiger** [comment]
That's true, but what should we do ? The map area should have a fixed size for GUI overlays and general GUI layout. So if we try to keep the proportions, we maybe only use a small part of the mini map area. Showing only a part of the map and make the mini map scrollable is too complicate at this point.
I say we keep it as it is and I say this is not a bug. maybe a feature request, but its not every likely that it will be done one day.

**Comment by andy5995** [comment]
I don't know how to best fix it.

I saw that this issue was first posted in the feature request forum. Here is the link for future reference: [Ingame minimap should keep the aspect ratio](https://forum.megaglest.org/index.php?topic=5886.0)

You've classified this as a feature request, not a bug, so...

Closing...
