### ISSUE TITLE
[map editor] "Save As" saves the file under the same name

### ISSUE THREAD

**Issue by andy5995** [MegaGlest/megaglest-source#177]
Using the git version, this reproduces every time.

Using "Save As" (and then typing in a filename) saves (and overwrites with no warning!) the map that was originally opened. It does not create a new file with the name given after "Save As" is selected.

I'm reasonably certain that's a newly introduced bug. I'd suggest looking at 588ec21d8a36c7193b8ad33857f36d5c3774b755

**Comment by titiger** [comment]
I checked in something, is it fixed now ?

**Comment by andy5995** [comment]
fix confirmed
