### ISSUE TITLE
Windows clients get OOS when using build from current git source

### ISSUE THREAD

**Issue by andy5995** [MegaGlest/megaglest-source#181]
This happened using a self-built binary on Windows using the latest git revision of the MG source.

Assuming it's not a build problem, that means a bug was introduced sometime between the release of 3.13.0 and the last time there was an update to the git source repo.

I don't have a stacktrace to share, but it reproduces every time when a Windows client is connected to a Linux host, after 4-8 minutes of game play.

**Comment by tomreyn** [comment]
Is the Linux server you're testing on also built from the same Git revision, then? Backward compatibility is not guaranteed.

**Comment by andy5995** [comment]
Yes, @tomreyn

**Comment by softcoder** [comment]
So both windows and linux were built with exactly the same git revision? Not just the same dev branch?

**Comment by andy5995** [comment]
Yes, Rev: 5687.12998eb

**Comment by tomreyn** [comment]
I was able to reproduce this. I was using our snapshot builds (and data package) on a fast Ubuntu 16.04.3 amd64 system, which was both participating as a headless server and as a graphical client, and a slow Windows 10 client (Atom CPU + Intel GPU), which went OOS during my first attack on the Conflict map (my two players were playing Indians, enemies were Norsemen and Magic).
