### ISSUE TITLE
Would you accept a pull renaming the "Indians" faction?

### ISSUE THREAD

**Issue by treymerkley** [MegaGlest/megaglest-source#194]
It's a cool game, but it's a little hard to recommend to my native friends. If I were to make a pull changing them to "Native Americans" or a specific tribe with the described characteristics, would you accept it, if it didn't break anything?

**Comment by tomreyn** [comment]
This is just a personal opinion of a less relevant contributor to the project: I'd love it - thanks for considering it, Trey. It's probably not just a coding task, though - if I remember correctly there are images which have "Indian(s)" rendered as text on them, too (those are probably scenarios).

I guess the final decision on this will have to come from @titiger.

**Comment by treymerkley** [comment]
Thanks for the feedback! If there is, we would need someone who can do art to fix it up. If we could get approval, that would be great. If we do, I'd like to get in contact with someone who knows more about the various tribes to help rework it into something that appeals to the standard player while also not making anyone feel unwelcome.

**Comment by ile6695** [comment]
You might also be interested in CPG Greys video about this topic [https://www.youtube.com/watch?v=kh88fVP2FWQ](https://www.youtube.com/watch?v=kh88fVP2FWQ)
Longer name is a bit less descriptive and while some do like to use it, some do not.

**Comment by andy5995** [comment]
> This is just a personal opinion of a less relevant contributor to the project: I'd love it - thanks for considering it, Trey. It's probably not just a coding task, though - if I remember correctly there are images which have "Indian(s)" rendered as text on them, too (those are probably scenarios).
> 
> I guess the final decision on this will have to come from @titiger.

I think this is a good idea as well @tomreyn and @treymerkley. And I don't consider a rename has having anything to do with "political correctness", but just plain accuracy. If I'm not mistaken, Indians are from India. The faction in MG clearly is based on Native Americans and has nothing to do with India. "Native Americans" seems kind of a long name for a faction, and using a specific tribe name might be the most suitable.

**Comment by titiger** [comment]
No, I want to keep the name. The faction is called like this for more than 15 years already !

**Comment by titiger** [comment]
No, I want to keep the name. The faction is called like this for more than 15 years already !

**Comment by andy5995** [comment]
@treymerkley I don't permissions to make the changes for the MegaGlest official data, but I've done it for one mod today: https://github.com/zetaglest/readypack-testing

If you're still interested in playing, I could make a mod that does what you ask, with no changes to the faction, other than changing the name.
