### ISSUE TITLE
Installing dependencies fails on Debian sid / bullseye

### ISSUE THREAD

**Issue by ile6695** [MegaGlest/megaglest-source#196]
I'm trying to build from source, but installing dependencies using the script does not install everything.
Running /mk/linux/setupBuildDeps.sh results in the following error

'The following packages have unmet dependencies:
 libwxgtk3.0-dev : Depends: wx3.0-headers (= 3.0.4+dfsg-14) but 3.0.4+dfsg-15 is to be installed
                   Depends: libwxbase3.0-dev (= 3.0.4+dfsg-14) but 3.0.4+dfsg-15 is to be installed
E: Unable to correct problems, you have held broken packages.
An error occurred while installing build dependencies.

Please report a bug at http://bugs.megaglest.org providing the following information:
--- snip ---
Git revision: 4846ad092e5d9f7ece582688754236af8569e09a
LSB support:  1
Distribution: Debian
Release:      unstable
Codename:     sid
Architecture: x86_64
--- snip ---'

I am able to install wx3.0-headers=3.0.4+dfsg-14 manually, but not libwxbase3.0-dev

**Comment by ile6695** [comment]
It seems that building is possible even when the setupBuildDeps.sh fails

**Comment by tomreyn** [comment]
From what I seem to remember, wxgtk is only needed for the map editor and model viewer (and previously for the configurator) utilities but not the main game (nor the game server).

[dak ls libwxgtk3.0-dev](https://qa.debian.org/madison.php?package=libwxgtk3.0-dev) suggests that no such package is currently available in Debian sid _for amd64_ (though it may have been when you filed this bug, or maybe you run a [mixed sid/testing system](https://wiki.debian.org/FAQsFromDebianUser#How_dangerous_is_it_to_run_a_mixed_system.3F)).  However, [packages.debian.org](https://packages.debian.org/search?suite=sid&keywords=libwxgtk3) suggests that there is a package libwxgtk3.0-gtk3-dev which may be what we're looking for in sid.

[libwxbase3.0-dev](https://qa.debian.org/madison.php?package=libwxbase3.0-dev) does exist in sid at this time.

**Comment by ile6695** [comment]
I was curious so I installed fresh debian on virtual machine. I used testing-iso, which I upgraded to unstable.
libwxgtk3.0-dev has no installation candidate, so this only confirms what tomreyn wrote.

**Comment by softcoder** [comment]
I changed the setup script to use the wx package name I see on sid: libwxgtk3.0-gtk3-dev

https://packages.debian.org/sid/libwxgtk3.0-gtk3-dev

**Comment by ile6695** [comment]
4654f695988ce147329d1de4aa9d35dfa93c83da does indeed seem to fix this issue.
Building using mk/linux/build-mg.sh works too and the game runs fine.
Map editor opens fine but terminal hints about segmentation fault when closing the window. Hopefully this does not happen on stable systems.
