### ISSUE TITLE
Will G3D going to be updated for the version 2.8 of blender

### ISSUE THREAD

**Issue by Monaturca** [MegaGlest/megaglest-source#198]
I know it can be solved by  using an older version of blender. I just wanted to ask. Will it be updated for the new version of blender?

**Comment by Jammyjamjamman** [comment]
Err... I started looking into this a while ago, but it was all completely new to me. I got as far as getting the general gist of how the new Blender API works. Had to postpone working on the script for other projects.

I would like to get back to work on this (taking a holiday next week, so perhaps then).

Or, if anyone else would like to work on this script that would be great :) . I'd be happy to give any info I've discovered so far on how to update the script.

**Comment by Monaturca** [comment]
I wish I could help, but unfortunately I don't know how to code. I'm just reverse engineering them and making really basic units. 

Thank you for replying. I hope your day goes well.

**Comment by Jammyjamjamman** [comment]
> I wish I could help, but unfortunately I don't know how to code. I'm just reverse engineering them and making really basic units.
> 
> Thank you for replying. I hope your day goes well.

If you want to make new G3D models in blender, my suggestion for now is to use blender 2.79: https://download.blender.org/release/Blender2.79/

**Comment by Jammyjamjamman** [comment]
Blender >=2.8 support here https://github.com/MegaGlest/megaglest-source/blob/develop/source/tools/glexemel/g3d_support_b269.py.
