### ISSUE TITLE
Problems with vbros mods

### ISSUE THREAD

**Issue by bztsrc** [MegaGlest/megaglest-source#210]
Hi,

I'm not sure where to report these. If this isn't the right place, could you please proxy my error report? Thank you very much!

Downloading _vbros_pack_1_ and _vbros_pack_2_ fails, and _vbros_pack_4_ installs successfully, but gives an error message when I try to play it, see the attached screenshot.
![megaglest_vbros4_err](https://user-images.githubusercontent.com/12779069/139233738-2afe39ed-a7ac-4d6d-8672-fb4262958d3c.png)
Any idea what to do? Is there something I can do or is this an error on the mods' side? I have already reinstalled vbros from the server, so this should be the latest version.

Thanks,
bzt

**Comment by tomreyn** [comment]
Hi bzt, sorry for the late response. 

I have not yet been able to check whether this is a generic issue.

In case it is not generic, but specific to your environment: 
* Can you check whether these files exist and permissions are set up properly (use `stat` or `ls -l` on these files)?
* A first guess would be that maybe the file system ran full (run `df -h` and `df -hi` against this path) or or contains inconsistencies (run `fsck` against the containing block device, probably while the file system is not mounted).

Thanks!

**Comment by andy5995** [comment]
@bztsrc The mod center doesn't have the latest files and they are indeed broken. @tomreyn I get the same results as @bztsrc.

The original mod author updated them and posted new links for them in December of 2019:

https://forum.megaglest.org/index.php?topic=4511.msg94074#msg94074

But the MG mod center hasn't been updated with the new info yet.

As noted in the forum post above, the most current download links are directly accessible from the [main post of the thread](https://forum.megaglest.org/index.php?topic=4511.0)

**Comment by titiger** [comment]
its fixed now and all is hosted on the megaglest server now so it wont happen again.

**Comment by bztsrc** [comment]
Thank you!
