### ISSUE TITLE
Double clicking on a game entry on  the load menu should load the game

### ISSUE THREAD

**Issue by Rampoina** [MegaGlest/megaglest-source#242]
For better UX it would be nice if double clicking on a saved game entry loaded the game instead of having to press the "Load Saved Game" button

**Comment by pavanvo** [comment]
@Rampoina  this check prevent second click https://github.com/MegaGlest/megaglest-source/blob/22a474b93bf95e29d3f784cf1a533d177e1c62a4/source/glest_game/menu/menu_state_load_game.cpp#L278

**Comment by pavanvo** [comment]
as I see, buttons haven't double click event, maybe we need to find all places for this improvements, before implement double click

**Comment by Rampoina** [comment]
@pavanvo I've added the event to the menus in  #243 , now any of them can implement it

>  maybe we need to find all places for this improvements, before implement double click

of course, If you can think of others mention it here or open an issue

Maybe on the mod menu, but that's not as  clear
