### ISSUE TITLE
libidn.so.11 not found

### ISSUE THREAD

**Issue by Frusadev** [MegaGlest/megaglest-source#271]
I just installed megaglest but i try runing it, i get this error:

./megaglest: error while loading shared libraries: libidn.so.11: cannot open shared object file: No such file or directory
![Screenshot_2023-09-28_22-06-09](https://github.com/MegaGlest/megaglest-source/assets/81917636/1becf162-6bdd-4b61-a106-ab83612b58c9)

OS: Ubuntu 23.04 lunar
Kernel: x86_64 Linux 6.2.0-33-generic
WM: OpenBox

**Comment by pavanvo** [comment]
AFAIK to fix it you can just rebuild it for you system.
You can olso check appImage from Pre-release - [snapshot]( https://github.com/MegaGlest/megaglest-source/releases/tag/snapshot)

**Comment by mornau** [comment]
How did you install?

Either use the installer provided, use a Linux distribution or third party package, or (optionally build it yourself and) set things up in your home directory manually and run ./start_megaglest
https://docs.megaglest.org/MG/FAQ#How_do_I_install_into_my_home_directory_or_bypassing_the_installer_on_Linux.3F

**Comment by Frusadev** [comment]
After running start_megaglest

OS info. [Ubuntu 23.04], Arch.[x86_64], Dir.[/home/frusadev/Downloads/megaglest-binary-linux-x86_64-3.13.0]
 Found LDCONFIG variable [1][/usr/sbin/ldconfig]...
- default library [liblber-2.4.so.2] is missing in your OS, attempting to find and link to different version if is available...
  new library link [.../lib/liblber-2.4.so.2] pointed to [/lib/x86_64-linux-gnu/liblber.so.2].
- default library [libldap_r-2.4.so.2] is missing in your OS, attempting to find and link to different version if is available...
  > not found !
- default library [libffi.so.6] is missing in your OS, attempting to find and link to different version if is available...
  new library link [.../lib/libffi.so.6] pointed to [/lib/x86_64-linux-gnu/libffi.so.8].
- default library [libFLAC.so.8] is missing in your OS, attempting to find and link to different version if is available...
  new library link [.../lib/libFLAC.so.8] pointed to [/lib/x86_64-linux-gnu/libFLAC.so.12].

Ignored libraries (please include in bug reports):
libpulse-simple.so.0 libXinerama.so.1 libXxf86vm.so.1 librt.so.1 libglapi.so.0 libXdamage.so.1 libxcb-glx.so.0 libxcb-dri2.so.0 libxcb-dri3.so.0 libxcb-present.so.0 libxcb-sync.so.1 libxshmfence.so.1 libsasl2.so.2 libgssapi.so.3 libjson-c.so.2 libheimntlm.so.0 libasn1.so.8 libhcrypto.so.4 libroken.so.18 libwrap.so.0 libwind.so.0 libheimbase.so.1 libhx509.so.5 libsqlite3.so.0 libcrypt.so.1 libnsl.so.1

**Comment by Frusasoft-frusadev** [comment]
After running start_megaglest

OS info. [Ubuntu 23.04], Arch.[x86_64], Dir.[/home/frusadev/Downloads/megaglest-binary-linux-x86_64-3.13.0]
 Found LDCONFIG variable [1][/usr/sbin/ldconfig]...
- default library [liblber-2.4.so.2] is missing in your OS, attempting to find and link to different version if is available...
  new library link [.../lib/liblber-2.4.so.2] pointed to [/lib/x86_64-linux-gnu/liblber.so.2].
- default library [libldap_r-2.4.so.2] is missing in your OS, attempting to find and link to different version if is available...
  > not found !
- default library [libffi.so.6] is missing in your OS, attempting to find and link to different version if is available...
  new library link [.../lib/libffi.so.6] pointed to [/lib/x86_64-linux-gnu/libffi.so.8].
- default library [libFLAC.so.8] is missing in your OS, attempting to find and link to different version if is available...
  new library link [.../lib/libFLAC.so.8] pointed to [/lib/x86_64-linux-gnu/libFLAC.so.12].

Ignored libraries (please include in bug reports):
libpulse-simple.so.0 libXinerama.so.1 libXxf86vm.so.1 librt.so.1 libglapi.so.0 libXdamage.so.1 libxcb-glx.so.0 libxcb-dri2.so.0 libxcb-dri3.so.0 libxcb-present.so.0 libxcb-sync.so.1 libxshmfence.so.1 libsasl2.so.2 libgssapi.so.3 libjson-c.so.2 libheimntlm.so.0 libasn1.so.8 libhcrypto.so.4 libroken.so.18 libwrap.so.0 libwind.so.0 libheimbase.so.1 libhx509.so.5 libsqlite3.so.0 libcrypt.so.1 libnsl.so.1

**Comment by Jammyjamjamman** [comment]
Try `sudo apt install libldap-common` and running `./start_megaglest` again.

**Comment by Frusadev** [comment]
Thanks
I've been able to solve the issue on own. I just installed the packages needed for building and it started working.

**Comment by Jammyjamjamman** [comment]
Glad you found a solution.
