### ISSUE TITLE
Source tarball: "fatal: Not a git repository" at each compilation step

### ISSUE THREAD

**Issue by akien-mga** [MegaGlest/megaglest-source#48]
When compiling MegaGlest 3.11.0 using your tar.xz source tarball, I get the following warnings at each compilation step:
```
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```
It's mostly a cosmetic issue, but it pollutes the logs a lot, so it would be nice if a check for the relevant git files could be done once during the CMake call, and then git integration would be disabled if the check fails.

**Comment by tomreyn** [comment]
We should indeed not blindly assume to be working in a Git repository.

**Comment by filux** [comment]
I can probably fix this in the tomorrow evening+.
