### ISSUE TITLE
CMake gets the version wrong in 3.11.0

### ISSUE THREAD

**Issue by akien-mga** [MegaGlest/megaglest-source#49]
In my CMake log, I have:
```
-- CMAKE_SOURCE_DIR = /home/akien/Mageia/Checkout/megaglest/BUILD/megaglest-3.11.0
-- Build type for this compile will be: release
-- Determining version number system type to use:
-- ** Trying 3 part versioning] 
-- MegaGlest Version is [3.9.0] 
```
I checked the source file in which the version is defined, and it is indeed set to 3.11.0, so there must be something wrong in the way CMake retrieves this value (in the same source file, "v3.9.0" is used to specify the latest save file compatible release).

**Comment by filux** [comment]
I can fix this in the evening or tomorrow.
