### ISSUE TITLE
Windows installer packaging issues

### ISSUE THREAD

**Issue by tomreyn** [MegaGlest/megaglest-source#51]
When packaging Windows installers, the blender directory is included, which contains both Windows and Linux binaries of some tools, as well as a Git repository meta file.

To do:
- Creating Windows installers should be a fully automated process to rule out human error and to allow for fast and regular releases (and hotfixes)
- Binaries should be built live before the installer is created, not included from a repository
- No Linux binaries should be included in the Windows installer
- No .git* files must be included (_export_ the blender directory, don't just _copy_ it)

**Comment by tomreyn** [comment]
Note that Filux has written packaging scripts for Annex - maybe we can reuse some of this code.

https://bitbucket.org/annexctw/annex/src/HEAD/mk_release/linux/make-release.sh?at=develop&fileviewer=file-view-default

**Comment by softcoder** [comment]
updated installer to not include .git folders and not include Linux binaries

**Comment by tomreyn** [comment]
@filux Could you comment on the other things? I assume you're most acquainted with Windows packaging at this time.

**Comment by filux** [comment]
> Creating Windows installers should be a fully automated process to rule out human error and to allow for fast and regular releases (and hotfixes)

around  this ^ will be a bit to do, for now installer is easy to make on "windows where exist binaries for one arch only" (so jenkins workspace fits)

> Binaries should be built live before the installer is created, not included from a repository

Well for now we have situation where "installers are created shortly after binaries were built" and imo this isn't a bad way and has even more pros than cons.
... and in situation when you are creating windows' installer on linux then imo "build binaries live ..." shouldn't be even considered.

Other points are most likely done as it was said.

**Comment by tomreyn** [comment]
Thanks for your feedback. I guess we can close this one then.
