### ISSUE TITLE
MACOS : "MegaGlest cannot be opened because of a problem."

### ISSUE THREAD

**Issue by skrytyy** [MegaGlest/megaglest-source#63]
I recently updated MegaGlest to the latest 3.11.1 release and every time I open the game I get a pop-up saying "MegaGlest cannot be opened because of a problem." I am running on MAC OSX Mavericks. Here is a screenshot of the pop-up.
![screen shot 2015-04-23 at 7 57 48 pm](https://cloud.githubusercontent.com/assets/12092290/7310526/3078f2aa-e9f3-11e4-8e5b-bce8656875ad.png)

It worked before I updated it. I have tried reinstalling it all the ways listed on your site. I have X11. I have even tried downloading the windows version and running it on Wine. Please help me figure this out. I know you don't have many people willing to test MegaGlest on a MAC but I am willing to help test. Thank you.

If you need specs on my computer I am willing to E-Mail them to you.

**Comment by Walkman100** [comment]
Looking quickly through it, it seems there's a missing file, under `Dyld Error Message:` it says `Library not loaded: /opt/local/lib/libSDL-1.2.0.dylib`
Seems you don't have a system library?

**Comment by skrytyy** [comment]
To me it looked as if the `Resources` folder was in the wrong spot. I tried moving the `Resources` folder to the `MACOS` folder and the game didn't even start. So I downloaded it again and still the same error.

Here is a picture of the `contents` folder just to make sure everything is where is should be.
![screen shot 2015-04-25 at 9 23 31 am](https://cloud.githubusercontent.com/assets/12092290/7333236/0a6b5432-eb2d-11e4-85aa-c22d734b6b4f.png)

Here is a picture of the `MACOS` folder.
![screen shot 2015-04-25 at 9 23 35 am](https://cloud.githubusercontent.com/assets/12092290/7333238/25e8a0ac-eb2d-11e4-8265-e1c422d95965.png)

One last picture of the `Resources` folder.
![screen shot 2015-04-25 at 9 27 08 am](https://cloud.githubusercontent.com/assets/12092290/7333240/54ab630c-eb2d-11e4-8cc8-1fd35daf07e4.png)

Inside the `megaglest-game` folder.
![screen shot 2015-04-25 at 9 27 22 am](https://cloud.githubusercontent.com/assets/12092290/7333243/682022e2-eb2d-11e4-821f-e621bbc049cd.png)

Hopefully this helped some. I'm trying to get this game to work because some friends and I are playing it at a LAN party tonight. Thank you.

**Comment by Walkman100** [comment]
Well you could probably use an old version, I'm guessing that since it's trying to access `/opt/` which is used on Linux and not a Mac, there's something wrong with this build.

**Comment by skrytyy** [comment]
Where do I get the old version?

**Comment by Walkman100** [comment]
From the [releases page](https://github.com/MegaGlest/megaglest-source/releases)

It seems the only other release with a Mac OS download is [v3.9.0](https://github.com/MegaGlest/megaglest-source/releases/tag/3.9.0)

**Comment by skrytyy** [comment]
Will it work with other versions?

**Comment by alketii** [comment]
Try 3.9.1, its a bit old, but i think mac version works there.

**Comment by Walkman100** [comment]
> Will it work with other versions?

I don't know, you will probably have to get everyone else to get the same version.

> Try 3.9.1, its a bit old, but i think mac version works there.

There is no Mac download for [3.9.1](https://github.com/MegaGlest/megaglest-source/releases/tag/3.9.1).

**Comment by skrytyy** [comment]
I think it's the last version I had.

**Comment by alketii** [comment]
Sorry it was 3.9.0 which is comparabile with 3.9.1

https://github.com/MegaGlest/megaglest-source/releases/download/3.9.0/MegaGlest_3.9-tomreyn1_macintel_osx.zip

**Comment by skrytyy** [comment]
Thanks!

**Comment by filux** [comment]
Please try next build (choose one link) and give to us some feedback:

[MegaGlest-game-macos-3.11.1.b1.dmg](https://github.com/MegaGlest/megaglest-source/releases/download/3.11.1/MegaGlest-game-macos-3.11.1.b1.dmg)

[MegaGlest-game-macos-3.11.1.b1.zip](https://github.com/MegaGlest/megaglest-source/releases/download/3.11.1/MegaGlest-game-macos-3.11.1.b1.zip)

**Comment by skrytyy** [comment]
Okay, Walkman. I have tried the two downloads that you sent me. `MegaGlest-game-macos-3.11.1.b1.dmg` came up with the same error.
![screen shot 2015-06-10 at 10 34 47 am](https://cloud.githubusercontent.com/assets/12092290/8086723/7b969b28-0f5c-11e5-9f5b-d17fa77bd4ce.png)

After that was unsuccessful I tried the second download. `MegaGlest-game-macos-3.11.1.b1.zip` also came up with the same error.
![screen shot 2015-06-10 at 10 37 20 am](https://cloud.githubusercontent.com/assets/12092290/8086804/e6f6746a-0f5c-11e5-87cf-6e347f8efffb.png)

Sorry for the wait btw. I have been meaning to get this feedback to you. I really enjoy this game and am willing to help get it running on my laptop. Thank you.

**Comment by tomreyn** [comment]
Please also keep an eye on this forum thread discussing what is likely the same issue:
https://forum.megaglest.org/index.php?topic=9708.0
There's not currently a complete solution available but you could give ONE of these a try, if you wanted (likely won't work, though):

https://github.com/MegaGlest/megaglest-source/releases/download/3.11.1/MegaGlest-game-macos-3.11.1.b2.dmg
https://github.com/MegaGlest/megaglest-source/releases/download/3.11.1/MegaGlest-game-macos-3.11.1.b2.zip

**Comment by filux** [comment]
Please try next build (choose one link) and give to us some feedback:

[MegaGlest-game-macos-3.11.1.b3.dmg](https://github.com/MegaGlest/megaglest-source/releases/download/3.11.1/MegaGlest-game-macos-3.11.1.b3.dmg]MegaGlest-game-macos-3.11.1.b3.dmg)

[MegaGlest-game-macos-3.11.1.b3.zip](https://github.com/MegaGlest/megaglest-source/releases/download/3.11.1/MegaGlest-game-macos-3.11.1.b3.zip)

**Comment by tomreyn** [comment]
This one has been [reported to work](https://forum.megaglest.org/index.php?topic=9708.msg91884;topicseen#msg91884) by another OS X user.

**Comment by skrytyy** [comment]
The `.zip` download works for me. Thank you so much!

**Comment by skrytyy** [comment]
The `.dmg` download didn't work.

**Comment by filux** [comment]
I bet it was link from email. During creating message link for .dmg was bugged, and fixed just few seconds later, but email was sent after "create" and nothing after "edit".

**Comment by skrytyy** [comment]
It was. Thank you so much!

**Comment by tomreyn** [comment]
Should we close this bug report then? The bug initially reported appears to be fixed?

**Comment by skrytyy** [comment]
Yes. Thank all of you for the help!
