### ISSUE TITLE
cmake >= 3.2.1 doesn't automatically add the X11 libs with Find_Package(OpenGL) anymore

### ISSUE THREAD

**Issue by filux** [MegaGlest/megaglest-source#65]
from IRC:

```
[00:58] <Mr_Bones_> any devs about?
[00:58] <Mr_Bones_> would be nice if https://bugs.gentoo.org/show_bug.cgi?id=548488 was fixed up in the CMake files
[00:58] <MGBot> Title: Bug 548488 dev-util/cmake-3.2.1 breaks games-strategy/megaglest-3.9.1-r1: ../shared_lib/liblibmegaglest.a(gl_wrap.cpp.o): undefined reference to symbol 'XFreeFont' (at bugs.gentoo.org)
[00:59] <Mr_Bones_> cmake >= 3.2.1 doesn't automatically add the X11 libs with Find_Package(OpenGL) anymore.
```

https://bugs.gentoo.org/show_bug.cgi?id=548488

**Comment by DAP-DarkneSS** [comment]
Seems to be the same at openSUSE:Factory:
[  449s] [100%] Building CXX object source/glest_game/CMakeFiles/megaglest.dir/world/tileset.cpp.o
[  462s] Linking CXX executable megaglest
[  463s] /usr/lib/gcc/i586-suse-linux/4.8/../../../../i586-suse-linux/bin/ld: ../shared_lib/liblibmegaglest.a(gl_wrap.cpp.o): undefined reference to symbol 'XLoadQueryFont'
[  463s] /usr/lib/libX11.so.6: error adding symbols: DSO missing from command line
[  463s] collect2: error: ld returned 1 exit status
[  463s] source/glest_game/CMakeFiles/megaglest.dir/build.make:2206: recipe for target 'source/glest_game/megaglest' failed
[  463s] make[2]: *** [source/glest_game/megaglest] Error 1
[  463s] CMakeFiles/Makefile2:176: recipe for target 'source/glest_game/CMakeFiles/megaglest.dir/all' failed
[  463s] make[1]: *** [source/glest_game/CMakeFiles/megaglest.dir/all] Error 2
[  463s] Makefile:136: recipe for target 'all' failed
[  463s] make: *** [all] Error 2

**Comment by DAP-DarkneSS** [comment]
Could you make a patch set for 3.11.1 or speed new release up please?

**Comment by filux** [comment]
Yes, we are think about new release soon, but there is a patch:

[megaglest-3.11.1_cmake3.2-x11.patch](http://filux.megaglest.org/patches/megaglest-3.11.1_cmake3.2-x11.patch)

**Comment by DAP-DarkneSS** [comment]
Thank you very much!
