### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kozross** [MegaGlest/megaglest-source#68]
While I know you guys are free software, it'd be nice to have a license file explaining what license you guys use.

**Comment by alketii** [comment]
Well it doesn't have a License file in source code, but its mentioned in every cpp file and in binary installers.

**Comment by tomreyn** [comment]
Did you actually spend time on looking for this information?

https://github.com/MegaGlest/megaglest-source/tree/master/docs

**Comment by tomreyn** [comment]
Sorry about the bad tone I picked, I was just disappointed that Koz was unable to spot the copyright declaration and license text in the "docs" subdirectory on his own.

Anyways, it's there, so this is not a bug - closing. (Please feel free to contact us by e-mail should you think differently or in case I misunderstood the bug report).
