### ISSUE TITLE
strange behavior in map editor after choosing "File>New"

### ISSUE THREAD

**Issue by filux** [MegaGlest/megaglest-source#75]
File > New > Ok and nothing happens, 
you first need to do something e.g. left click on the map to see new map.

```
[ Debian ] [ testing ] [ stretch ] [ x86_64 ]
[5170.02fe61e]
Using wxWidgets version [2.8.12.1]
```

**Comment by alketii** [comment]
Confirmed. I thought this was present like always.

**Comment by filux** [comment]
Maybe yes, I am not using map editor much :D, the question is does this should work like now or is it a bug.

**Comment by softcoder** [comment]
Should be fixed

**Comment by filux** [comment]
Yep.
