### ISSUE TITLE
sdl2:  In the Polish language is not possible to write special character "ę" (RAlt+e)

### ISSUE THREAD

**Issue by filux** [MegaGlest/megaglest-source#78]
RAlt+e wrongly enables some modifier (something like "g" with hat ![g with hat](https://cloud.githubusercontent.com/assets/5335953/10400877/c552fb3a-6ebb-11e5-8f7f-94564192be6e.png) )
and then you can write another character which is modified in most cases by adding something under or on top of it. 
Key test for RAlt+e shows ("A" with 2 dots on top) -60,-60,512
![notfullscreen2](https://cloud.githubusercontent.com/assets/5335953/10400886/d239e34a-6ebb-11e5-9393-a63b2eea096c.png).

Normally character "ę" should be created instant by single use RAlt+e. In the Polish language don't exist "accents" produced "in two steps" at all.

**Comment by softcoder** [comment]
What screen is this defect referring to?

**Comment by filux** [comment]
Both. First screen ("g" with hat) is in game chat after single RAlt+e (enabled some modifier mode and waits for next letter). Second screen shows in game key test for RAlt+e.
In both cases expected is "ę" character.

**Comment by softcoder** [comment]
Which page in the game are you typing this.

**Comment by filux** [comment]
1-st screen.  New Game > Custom Game > Play now > Enter > RAlt+e   (in the chat, single use RAlt+e)
2-nd screen.  Options > Keyboard setup > RAlt+e   (in the key test box)

**Comment by titiger** [comment]
I have similar issues with the Euro ( € ) character. I cannot input it in irc chat in the lobby for example.

**Comment by filux** [comment]
a bit unrelated but also  ctrl+L - hidden language menu doesn't work

**Comment by filux** [comment]
since 6d0592d RAlt+e works different but still wrong (single use RAlt+e), because produces "e" and "g with hat" at once
![wrongletter](https://cloud.githubusercontent.com/assets/5335953/10563105/9717b3b6-757b-11e5-96f9-d628b77f2532.png)

**Comment by filux** [comment]
today I got idea about check/compare codes in key test, because maybe this may be somehow helpful, so now (sdl2) I see:
- for "e" : 101,101,0
- for "RAlt": 1073742054,1073742054,512
- for "RAlt+e": -60,-60,512

... and for old values (sdl1 / 3.11.1) I see:

- for "e" : 101,101,101,0
- for "RAlt": 313,313,0,16384
- for "RAlt+e": 101,281,281,16384

... so 3 values vs 4 values and for sure this long sdl2 numbers for "RAlt" looks strange

**Comment by titiger** [comment]
Suggestion: currently we use key events like MainMenu::keyPress and so on.
Thats ok for normal button pressed events in the game and so on. For real textinput ( active text input label ) its maybe better to use a new SDL2 way and use SDL_TextInputEvent directly in the places where text input is needed.

**Comment by filux** [comment]
on 76d41df in game I don't see any difference:
![wrongletter3](https://cloud.githubusercontent.com/assets/5335953/10711565/ed58b01e-7a7f-11e5-8ac8-c26983b044bd.png)

... on the "headless configuration screen" is the same situation:
![wrongletter2](https://cloud.githubusercontent.com/assets/5335953/10711568/f69ec28a-7a7f-11e5-944c-c57448d6ade2.png)

... but in the lobby I see something different (first time I tested here, didn't expected differencess):
![wrongletter1](https://cloud.githubusercontent.com/assets/5335953/10711569/ffeaea08-7a7f-11e5-9dbf-41eacc9822e9.png)
so in the lobby is very close (e + proper and expected: "ę").

**Comment by filux** [comment]
on 964c776 in game still old behavior ^.
... in the lobby "ę" works but backspace doesn't work at all, so you can't remove characters.

**Comment by filux** [comment]
on 81346ba all looks to be fixed :)
