### ISSUE TITLE
False positive error

### ISSUE THREAD

**Issue by filux** [MegaGlest/megaglest-source#91]
titi as host, me as client, game won (was end message)

When host player disconnects from the game but game was won/lost then this message shouldn't be displayed at all and exit status for sure should be 0 (if it isn't, not checked).

``` c++
megaglest v3.12-dev                                                                                                                                          
Compiled using: GNUC: 50201 [64bit] platform: Linux-X64 endianness: little                                                                                   
GIT: [Rev: 5293.01673db] - using STREFLOP [SSE] - [no-denormals]                                                                                             
                                                                                         
*ERROR* [2015-12-13 00:36:06] In [network_interface.cpp::DisplayErrorMessage Line: 198] sErr [Player filux, disconnected from the game.] 
```

**Comment by softcoder** [comment]
no idea what this means: (if it isn't, not checked)

**Comment by tomreyn** [comment]
I assume Filux is saying that we should not report an ERROR event when a player disconnects, since this can and often is not unexpected behaviour, especially when a game is over. 

I guess it would be OK to WARN about players disconnecting (on purpose or not), but I think this should be limited to --verbose, not be reported on standard output / error by default.

**Comment by filux** [comment]
I am talking about single case when `battle is finished`, then any disconnection is in 99.99% cases done by user (host/admin) which did it himself and other players are confused by `fake error`.

One more time:
battle end + host/admin left the battle as first = others are disconnected (< normal) and ``see this error`` (< abnormal).

**Comment by titiger** [comment]
no more error is shown
