### ISSUE TITLE
Mouse can disappear on alt+tab

### ISSUE THREAD

**Issue by titiger** [MegaGlest/megaglest-source#94]
I myself  never had this problem, but for example tomreyn reported that he had no more mouse pointer after tabbing out in windows. The hotkey for native/game mouse pointer brought the mouse pointer back again. I don't know who told me , but someone had the same behaviour on linux too.

**Comment by tomreyn** [comment]
This is only an issue when No2DMouseRendering is set to 1 or you pressed the slash key to replace the game drawn red triangle by the OS mouse pointer.

So with the OS pointer active, when you press Alt-Tab to tab out of the game, release, then Alt-Tab again to tab back into the game, you end up with no mouse pointer at all. 

Pressing slash will bring back the red triangle pointer, but this is just a workaround.

**Comment by titiger** [comment]
maybe an implicit toggle native/non native mouse helps

**Comment by titiger** [comment]
very likely fixed now , but I contacted atze to test his issue too ( which is maybe the same ) before I close this.

**Comment by tomreyn** [comment]
I also think this is fixed now. Thanks!
