### ISSUE TITLE
Add tag 3.9.0.4

### ISSUE THREAD

**Issue by monwarez** [MegaGlest/megaglest-source#96]
It could be great to have a 3.9.0.4 tag for megaglest , it will allow to fetch the source for FreeBSD port

**Comment by tomreyn** [comment]
That's not a version we released, though. 

I seem to lack understanding of why you would ask for this, so here are some questions to better understand your intentions / needs:

* Which commit would you like to be tagged with this version number?
* Why would you want any commit tagged with a version number which was never used for a release?
* Why do you care about 3.9.* when the latest stable release is 3.11.1?

**Comment by tomreyn** [comment]
Whoops, looks like I can be wrong, since there is 
https://github.com/MegaGlest/megaglest-source/releases/download/3.9.0/megaglest-source-3.9.0.4.tar.xz
Unfortunately I do not know which commit this tarball matches. Maybe the person who produced it (I suspect this can be Softcoder) can tell.

**Comment by tomreyn** [comment]
According to my IRC logs, the 3.9.0.4 source package was produced by Softcoder on request of (Gentoo developer / packager) hasufell between 20131120 20:00 CET (+0100) and 20131120 20:03 CET (+0100). 

Subversion commits around the time can be reviewed on sourceforge at
http://sourceforge.net/p/megaglest/code/HEAD/log/?path=/trunk
(I do not know which time zone these display in.)

**Comment by monwarez** [comment]
I does not spend too much time on it , I know that 3.11.1 is released for almost a year , is just that I never get to build it on FreeBSD (if I remember correctly)

**Comment by monwarez** [comment]
I finally succeed to build 3.11.1 on FreeBSD with the port infrastructure so that the 3.9.0.4 tag is not needed anymore (unless someone else need it) . I think we can close the issue
