### ISSUE TITLE
Short hangs on network games - Windows only

### ISSUE THREAD

**Issue by tomreyn** [MegaGlest/megaglest-source#99]
**Issue description**

On Windows I notice short hangs, repeating in regular intervals. With a lower spec dedicated graphics card they render the game unplayable. With a current mid range / mobile graphics card they are still noticeable and are a minor nuisance. 

**Reproducing the issue**

Use the CI snapshot builds from http://snapshots.megaglest.org.

Be sure to enable the rain effect both on menus and in-game to reproduce. Since during hangs the rain will pause it makes it quite visible when they occur. Use the game rendered red triangle mouse pointer, not the OS one.

Use a 64-bit x86 build of Windows (reproduced on Windows 8.1 and 10) and join a game lobby (who hosts and whether it is a headless server does not matter). As soon as another Internet player (have not tested on LAN) joins you on the game lobby, the rain drops will hang for some dozen milliseconds in a ~5 second interval. Try moving the mouse pointer from the left edge to the right edge of your screen as quickly as possible, and notice whether it moves steadily (may not be reproducible on faster systems this way). 

Start the game. From the start, but still 10+ minutes into the game (so during the entire game) you should notice the rain drops hanging shortly in ~5s intervals, and everything else, too. Rendering just pauses for some dozen milliseconds. On lower spec hardware, this makes it hardly possible to play the game, impossible to win against an evenly skilled opponent. On higher spec hardware it is a nuisance, making the game feel unfit / non-polished for this platform.

If you keep FPS showing, you notice a ~ 20-30% drop in RenderFPS whenever this occurs.

**Test systems**

*System 1 ("atibox")* - lower spec desktop computer: 
* Intel [Core2 Quad Q9400](http://cpubenchmark.net/cpu.php?id=1045)
* ATI/AMD [Radeon HD 4670](http://videocardbenchmark.net/gpu.php?id=505)
* 8 GB RAM (DDR2)
* Windows 10 (x86_64), booted off an external 3,5'' 5400 UPM HDD
* MegaGlest installer registry modification applied
* Up to ~ 50 RenderFPS in-game

Using the same hardware on Linux (but booting off RAID-1 [SSHD](https://en.wikipedia.org/wiki/Hybrid_drive#Solid-state_hybrid_drive)), this issue does not occur, and I can play fine. Since there is no noticeable disk access (no disk sound, drive activity LED not lighting up much) during the times when this occurs, I do not think that the disk is the bottleneck here. 

*System 2 ("lenovo")* - higher spec laptop computer: 
* Intel [Core i7-4710MQ](http://cpubenchmark.net/cpu.php?id=2219)
* Intel [HD Graphics 4600](http://videocardbenchmark.net/gpu.php?id=2451)
* Nvidia [GeForce GT 730M](http://videocardbenchmark.net/gpu.php?id=2417)
* 8 GB RAM (DDR3)
* Windows 10 (x86_64), booted off an internal 2'' SSD (Samsung 840 EVO OEM variant)
* MegaGlest installer registry modification *not* applied
* Up to ~ 100 RenderFPS in-game

The graphics chipset in use during tests was the Intel (GPU) one. According to VideocardBenchmark.net, performance of the two graphics chips in this system is not all that different, though. Since this is an SSD backed system, and it is still susceptible to the hangs, this seems to further rule out disk I/O as the bottleneck causing this.

**Comment by titiger** [comment]
Problem still exists in  3814b9317fdd17d087614971336b053855832b36
And we got a complete freeze of a windows client there too after playing 5 minutes.

**Comment by softcoder** [comment]
Latest git head should have this resolved for the lobby, and hopefully also in game

**Comment by tomreyn** [comment]
Thanks. It is not entirely gone for me, but the impact is now so low that I consider this to have been rendered irrelevant. On *lenovo*'s HD 4600 GPU rain stalls only for the glimpse of an eye now.

**Comment by titiger** [comment]
Can we close this ? Fro me this is fixed
